# Generated by Django 5.0.3 on 2024-03-23 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavengerHunt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название задания')),
                ('type', models.IntegerField(choices=[(0, 'Простая задача')], default=0)),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('answer', models.TextField(verbose_name='Правильный ответ')),
            ],
        ),
        migrations.AlterField(
            model_name='botuserstate',
            name='state',
            field=models.IntegerField(choices=[(0, 'Регистрация'), (1, 'Решает'), (2, 'Ходит по меню')], default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='unique_team_id',
            field=models.CharField(default='a046cfd8-6a3b-47be-a013-6cc5fd0a67f8', max_length=40, unique=True, verbose_name='Идентификатор команды'),
        ),
        migrations.AddField(
            model_name='botuserstate',
            name='task',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='scavengerHunt.task'),
        ),
    ]
