# Generated by Django 5.0.3 on 2024-03-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavengerHunt', '0002_task_alter_botuserstate_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='unique_team_id',
            field=models.CharField(default='26422bad-6fb0-47b1-b337-1e7c68669f9b', max_length=40, unique=True, verbose_name='Идентификатор команды'),
        ),
    ]
